# SPDX-FileCopyrightText: German Aerospace Center (DLR) <cosmoscout@dlr.de>
# SPDX-License-Identifier: CC0-1.0

name: Check Compliance with REUSE Specification

on:
  push:
    branches:
      - '**'

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run REUSE Compliance Check
        uses: fsfe/reuse-action@v1
